version: 2
updates:
    - package-ecosystem: 'pip'
      directory: '/'
      schedule:
          interval: 'daily'

    # Enable version updates for Docker
    - package-ecosystem: 'docker'
      # Look for a `Dockerfile` in the `root` directory
      directory: '/'
      schedule:
          interval: 'weekly'
