name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bandit Security Scan
        run: bandit -r ./ --severity-level high --confidence-level all

      - name: Run Pip Audit
        run: pip-audit

      - name: Run Safety Security Check
        run: safety check -r requirements.txt
